- hosts: all
  remote_user: root
  become: yes
  pre_tasks:
    - name: Install dependencies.
      package: "name={{ item }} state=present"
      with_items:
        - epel-release
        - unzip
    - name: install updates
      yum: name=* state=latest
  roles:
    - sonar
