---

base_postgres_m: 9.6
base_postgres_s: 96
base_postgres_p: 3
base_postgres_jdbc_url: "https://jdbc.postgresql.org//download/postgresql-42.0.0.jar"

base_postgres_net: samenet
base_postgres_role: master
base_postgres_user: testuser
base_postgres_pass: testpass


base_postgres_repo: "https://yum.postgresql.org/{{ base_postgres_m }}/redhat/rhel-{{ ansible_distribution_major_version }}-x86_64/pgdg-centos{{ base_postgres_s }}-{{ base_postgres_m }}-{{ base_postgres_p}}.noarch.rpm"

base_postgres_packages:
  - postgresql{{ base_postgres_s }}-server
  - postgresql{{ base_postgres_s }}-contrib
  - perl-DBD-Pg
  - python-pip
  - python-psycopg2

base_postgres_pips:
  - pexpect

# I never dared changing:
base_postgres_port: 5432
