---

galaxy_info:
  author: Bas Meijer
  description: PostgreSQL on one or two Centos/RHEL boxes.
  company:
  license: license (MIT)
  min_ansible_version: 1.9
  platforms:
    - name: EL
      versions:
        - 6
        - 7

  galaxy_tags: ['databases']
dependencies: []
  # List your role dependencies here, one per line. Only
  # dependencies available via galaxy should be listed here.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
